spring:
  application:
    name: spring-security
  jpa:
    # Provide database platform that is being used
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      # New database is created when application starts and destroyed when application is stopped
      ddl-auto: create-drop
    # Show sql when spring data jpa performs query
    show-sql: true
    properties:
      hibernate:
        # Format queries
        format_sql: true
  datasource:
    # URL connection to database (replace <HOST>, <PORT>, and <DB_NAME> with your MySQL details)
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
    # MySQL driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: m@3lich

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
